version: "3.1"

services:
  postgresql:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - .:/srv/service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgresql